import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    marginTop: 8,
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 4,
  },
  textInput: {
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 16,
    color: '#000000',
  },
  inputError: {
    borderColor: '#CB3D40',
  },
  errorText: {
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 16,
    color: '#CB3D40',
  },
  errorContainer: {
    height: 16,
  },
  hintText: {
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 16,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  title: {
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: '#000000',
    paddingTop: 10,
    marginBottom: 10,
  },
  radioContainer: {
    flexDirection: 'column',
    paddingHorizontal: 10,
  },
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  radioButton: {
    height: 15,
    width: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#009BBD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonSelected: {
    height: 5,
    width: 5,
    borderRadius: 5,
    backgroundColor: '#009BBD',
  },
  label: {
    marginLeft: 10,
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 24,
    color: '#000000',
  },
  photoUploadContainer: {
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  photoUploadText: {
    fontFamily: 'Nunito Sans',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: '#000000',
  },
  uploadButton: {
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  uploadButtonText: {
    fontFamily: 'Nunito Sans',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
    color: '#009BBD',
  },
  signUpButton: {
    alignSelf: 'center',
    width: 140,
    height: 48,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#DEDEDE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signUpButtonError: {
    backgroundColor: '#F4E041',
  },
  signUpButtonText: {
    fontFamily: 'Nunito Sans',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.1,
    textAlign: 'center',
    color: '#000000',
  },
});
